services:
  - type: web
    name: dtpa-telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: COLLEGE_SITE
        sync: false